# Generated by Django 5.0.2 on 2024-06-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0004_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
