# Generated by Django 5.0.2 on 2024-06-17 04:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0006_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='UserStatus',
        ),
    ]
