# Generated by Django 5.0.2 on 2024-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('wayapp', '0012_alter_jobdescription_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='file_jpost',
            field=models.FileField(null=True, upload_to='uploadsjp/% Y/% m/% d/'),
        ),
    ]
