# Generated by Django 5.0.2 on 2025-01-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0013_jobpost_file_jpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='file_jpost',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='company_name',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='contact_number',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='email',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applicant_contact_number',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='email',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='file_upload_CV',
            field=models.FileField(default='NULL', null=True, upload_to='uploadsjp/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='file_upload',
            field=models.FileField(default='NULL', null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
