# Generated by Django 5.0.2 on 2025-01-09 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0014_remove_jobpost_file_jpost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='username',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='username',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='intern', to=settings.AUTH_USER_MODEL),
        ),
    ]
