# Generated by Django 5.0.2 on 2025-01-10 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0015_remove_jobdescription_employer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='username',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
