# Generated by Django 5.0.2 on 2025-01-10 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0017_remove_jobdescription_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='user_name',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='username',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='username',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='intern', to=settings.AUTH_USER_MODEL),
        ),
    ]
