# Generated by Django 5.0.2 on 2025-01-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0018_remove_jobdescription_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='file_upload',
            field=models.FileField(default='NULL', null=True, upload_to='uploads_JD/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_requirements',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='qualifications',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='biography',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='curricular_skills',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='file_upload_CV',
            field=models.FileField(default='NULL', null=True, upload_to='uploads_CV/'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='noncurricular_skills',
            field=models.TextField(max_length=2000),
        ),
    ]
