# Generated by Django 5.0.2 on 2025-01-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0019_alter_jobdescription_file_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchInterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_contact_number', models.CharField(default='0', max_length=50)),
                ('email', models.CharField(default='0', max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('curricular_skills', models.TextField(max_length=2000)),
            ],
        ),
    ]
