# Generated by Django 5.0.2 on 2025-01-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0020_searchinterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='username',
        ),
        migrations.DeleteModel(
            name='SearchInterns',
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
