# Generated by Django 5.0.2 on 2025-01-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0021_remove_search_username_delete_searchinterns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='file_upload',
            field=models.FileField(default='NULL', null=True, upload_to='uploads_JD/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='GPA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='applicant_contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='file_upload_CV',
            field=models.FileField(default='NULL', null=True, upload_to='uploads_CV/%y/%m/%d/'),
        ),
    ]
