# Generated by Django 5.0.2 on 2025-01-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0023_alter_jobdescription_email_alter_jobpost_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
