# Generated by Django 5.0.2 on 2025-01-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0024_alter_jobdescription_email_alter_jobpost_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='id',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_description_ID',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
