# Generated by Django 5.0.2 on 2025-01-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0025_remove_jobdescription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='job_description_ID',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='jd_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_requirements',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='qualifications',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='biography',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='curricular_skills',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='noncurricular_skills',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='school',
            field=models.CharField(max_length=200),
        ),
    ]
