# Generated by Django 5.0.2 on 2025-01-17 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0026_remove_jobdescription_job_description_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='username',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='username',
            field=models.ManyToManyField(related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
    ]
