# Generated by Django 5.0.2 on 2025-01-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0027_remove_jobdescription_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='username',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
