# Generated by Django 5.0.2 on 2025-01-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayapp', '0028_remove_jobdescription_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='contact_person',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='first_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='last_name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
